apiVersion: v1
kind: ConfigMap
metadata:
  name: nmap-pipeline-config
data:
  main_01_input.conf: |
    input {
       http {
        port => 8080
        codec => json
      }
      
    }
  main_02_filter.conf: |
    filter {
      split {
        field => "hosts"
      }

      mutate {
        rename => {
          "[hosts][ip]" => "ip_address"
          "[hosts][status]" => "host_status"
          "[hosts][reason]" => "status_reason"
          "[hosts][hostname]" => "hostname"
        }
        remove_field => ["event", "http", "url", "user_agent", "hosts"]
      }

      date {
        match => [ "timestamp", "ISO8601" ]
        target => "@timestamp"
      }
    }
  main_03_output.conf: |
    output {
      elasticsearch {
        hosts => ["https://elasticsearch-master:9200"]
        ssl => true
        cacert => "/usr/share/logstash/config/certs/ca.crt"
        user => "elastic"   # Replace with actual username if authentication is required
        password => "1Qgd0A1BkFxmVuqZ"
      }
      stdout {
        codec => rubydebug
      }
    }
 
