apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  namespace: elasticsearch
spec:
  type: NodePort
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 30920  # You can choose any available port between 30000-32767
  selector:
    app: elasticsearch-master  # Update this to match the Pods' labels
