apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-pvc-2
  namespace: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
