apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-client-pvc-0
  namespace: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
